-- Compatibility pointer. The production schema is managed as ordered migrations.
-- Apply all files in supabase/migrations with `supabase db push`.
-- Current baseline: migrations/202607130001_mvp_schema.sql
